# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "build and distribute app"
  lane :build_and_distribute do
    sync_code_signing(
      type: "adhoc",
      app_identifier: "io.pepup.tools",
      git_url: "https://github.com/hdpinc/dummy-health-data-generator-certificates.git",
      readonly: true
    )
    build_app(
      scheme: "HealthKitTestData",
      configuration: "Release",
      export_method: "ad-hoc"
    )
  end
end
